const { sequelize } = require("../../config/mssql");
const { DataTypes } = require("sequelize");

const GlobalesRuteo = sequelize.define(
  "GLOBALES_RUTEO",
  {
    CORP_NIT: {
      type: DataTypes.STRING,
      primaryKey: true,
    },
    CORP_NOMBRE: { type: DataTypes.STRING },
    CORP_DIRECCION: { type: DataTypes.STRING },
    CORP_TELEFONO: { type: DataTypes.STRING },
    CORP_SLOGAN: { type: DataTypes.STRING },
    CORP_WEB: { type: DataTypes.STRING },
    CORP_EMAIL: { type: DataTypes.STRING },
    CORP_FAX: { type: DataTypes.STRING },
    CORP_NRC: { type: DataTypes.STRING },
    CORP_GIRO: { type: DataTypes.STRING },
    APLICA_RECARGO: { type: DataTypes.STRING },
    PORC_RECARGO: { type: DataTypes.DECIMAL },
    USUARIO_ALDO: { type: DataTypes.STRING },
    PASSWORD_ALDO: { type: DataTypes.STRING },
    COMPANIAS: { type: DataTypes.TEXT },
    CORREOS_EXAC_ALDO: { type: DataTypes.STRING },
    CORREOS_ALDO_EXAC: { type: DataTypes.STRING },
    COPIAR_RUTAS: { type: DataTypes.STRING },
    CAM_LST_PRC: { type: DataTypes.STRING },
    CAM_CON_PG: { type: DataTypes.STRING },
    CAM_PAIS: { type: DataTypes.STRING },
    CAM_CLA_PED: { type: DataTypes.STRING },
    HISTORICO_PEDIDOS: { type: DataTypes.STRING },
    CANTIDAD_MESES: { type: DataTypes.INTEGER },
    ESQUEMA_DESC: { type: DataTypes.STRING },
    USA_CONSIGNACION: { type: DataTypes.STRING },
    COBRO_MAL_ESTADO: { type: DataTypes.STRING },
    USA_RUTA_CLIENTE: { type: DataTypes.STRING },
    USA_BODEGA_FA: { type: DataTypes.STRING },
    SUGERIR_LOTES: { type: DataTypes.STRING },
    SUG_LOCALIZACION: { type: DataTypes.STRING },
    GENERAR_BITACORA: { type: DataTypes.STRING },
    USA_RUTEO: { type: DataTypes.STRING },
    SUBTIPO_RECIBO: { type: DataTypes.INTEGER },
    CONSECUTIVO: { type: DataTypes.STRING },
    COBROS_FACTURA_CONTADO: { type: DataTypes.STRING },
    RECAL_PRECIO: { type: DataTypes.STRING },
    HISTORICO_FACTURA: { type: DataTypes.STRING },
    CANTIDAD_MESES_FAC: { type: DataTypes.INTEGER },
    SUBTIPO_NOTACREDITO: { type: DataTypes.INTEGER },
    RUTA_EMM: { type: DataTypes.STRING },
    USA_SUG_VENTA: { type: DataTypes.STRING },
    USA_RUBROS_JORNADA: { type: DataTypes.STRING },
    Rubro1_JORNADA: { type: DataTypes.STRING },
    Rubro2_JORNADA: { type: DataTypes.STRING },
    Rubro3_JORNADA: { type: DataTypes.STRING },
    Rubro4_JORNADA: { type: DataTypes.STRING },
    Rubro5_JORNADA: { type: DataTypes.STRING },
    SOPORTE_TRASIEGOS: { type: DataTypes.STRING },
    USA_ENVASES: { type: DataTypes.STRING },
    VERIF_TOMAFISICA: { type: DataTypes.STRING },
    PERMITIDO_FALTANTE: { type: DataTypes.DECIMAL(28, 8) },
    VERIF_CARGAS: { type: DataTypes.STRING },
    PRONTO_PAGO_TOTALES: { type: DataTypes.STRING },
    PORCENTAJE_RESOLUCION: { type: DataTypes.INTEGER },
    PED_TEMP: { type: DataTypes.STRING },
    ESQUEMA_RESOLUCIONES: { type: DataTypes.STRING },
    SINCRO_DESATENDIDA: { type: DataTypes.STRING },
    OPT_BUSQ_ARTICULO: { type: DataTypes.STRING },
    VALIDA_LOTE_DEV: { type: DataTypes.STRING },
    ENTEROS_PEDIDO: { type: DataTypes.STRING },
    SUBTIPO_OTROCREDITO: { type: DataTypes.INTEGER },
    DESCUENTO_PRONTO_PAGO: { type: DataTypes.STRING },
    CANTIDAD_DIAS: { type: DataTypes.INTEGER },
    CANT_TIEMPO_TRASL: { type: DataTypes.STRING },
    CLR_RUTA_PROG: { type: DataTypes.STRING },
    CLR_RUTA_EJEC: { type: DataTypes.STRING },
    CLR_VISITA_FUERA: { type: DataTypes.STRING },
    CLR_TRASLADO_ADV: { type: DataTypes.STRING },
    CLR_VISITA_SIN_GPS: { type: DataTypes.STRING },
    CLR_VISITA_GPS_FUERA: { type: DataTypes.STRING },
    CARGA_EN_PROCESO: { type: DataTypes.STRING },
  },
  {
    schema: "ERPADMIN",
    timestamps: false,
  }
);

module.exports = GlobalesRuteo;
